# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depotname', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepotContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bought_at', models.FloatField()),
                ('date', models.DateTimeField()),
                ('depotname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockplot.Depot')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('stockExchange', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('sourceName', models.CharField(max_length=100)),
                ('sourceSymbol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.IntegerField(db_index=True)),
                ('date', models.FloatField(db_index=True)),
                ('open_price', models.FloatField(blank=True, default=None, null=True)),
                ('adj_open', models.FloatField(blank=True, default=None, null=True)),
                ('high', models.FloatField(blank=True, default=None, null=True)),
                ('adj_high', models.FloatField(blank=True, default=None, null=True)),
                ('low', models.FloatField(blank=True, default=None, null=True)),
                ('adj_low', models.FloatField(blank=True, default=None, null=True)),
                ('close', models.FloatField(blank=True, default=None, null=True)),
                ('adj_close', models.FloatField(blank=True, default=None, null=True)),
                ('change', models.FloatField(blank=True, default=None, null=True)),
                ('traded_volume', models.FloatField(blank=True, default=None, null=True)),
                ('adj_volume', models.FloatField(blank=True, default=None, null=True)),
                ('turnover', models.FloatField(blank=True, default=None, null=True)),
                ('last_price_of_the_day', models.FloatField(blank=True, default=None, null=True)),
                ('daily_traded_units', models.FloatField(blank=True, default=None, null=True)),
                ('daily_turnover', models.FloatField(blank=True, default=None, null=True)),
                ('ex_dividend', models.FloatField(blank=True, default=None, null=True)),
                ('split_ratio', models.FloatField(blank=True, default=None, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockplot.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='depotcontent',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockplot.Stock'),
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together=set([('stockid', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='depotcontent',
            unique_together=set([('depotname', 'stock')]),
        ),
        migrations.AlterUniqueTogether(
            name='depot',
            unique_together=set([('user', 'depotname')]),
        ),
    ]
