# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='id',
        ),
        migrations.AlterField(
            model_name='depot',
            name='depotname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
