# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0002_auto_20160319_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='QuandlName',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
