# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0003_auto_20160410_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskClass', models.IntegerField(blank=True, default=0, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('companyScore', models.IntegerField(blank=True, default=0, null=True)),
                ('balanceScore', models.IntegerField(blank=True, default=0, null=True)),
                ('analysisScore', models.IntegerField(blank=True, default=0, null=True)),
                ('newsScore', models.IntegerField(blank=True, default=0, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockplot.Stock')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockscore',
            unique_together=set([('stock', 'riskClass')]),
        ),
    ]
