# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0004_stockdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
