# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0005_depot_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='available',
            field=models.FloatField(default=94215),
            preserve_default=False,
        ),
    ]
