# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0005_auto_20160325_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='symbol',
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
    ]
