# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0006_depot_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depotcontent',
            old_name='bought_at',
            new_name='price',
        ),
        migrations.AddField(
            model_name='depotcontent',
            name='fee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
