# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0006_auto_20160325_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open_price', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change', models.FloatField()),
                ('traded_volume', models.IntegerField()),
                ('turnover', models.IntegerField()),
                ('last_price_of_the_day', models.FloatField()),
                ('daily_traded_units', models.IntegerField()),
                ('daily_turnover', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockplot.Stock')),
            ],
        ),
    ]
