# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0007_auto_20160424_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fundamentalsCompNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fundamentalsSymbol',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
