# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0008_auto_20161218_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotcontent',
            name='maxSinceBought',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
