# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0008_auto_20160326_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='change',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='close',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='daily_traded_units',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='daily_turnover',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='last_price_of_the_day',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='traded_volume',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='turnover',
        ),
    ]
