# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0009_depotcontent_maxsincebought'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFundamentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.IntegerField(db_index=True)),
                ('date', models.FloatField(db_index=True)),
                ('shares', models.FloatField(blank=True, default=None, null=True)),
                ('capitalization', models.FloatField(blank=True, default=None, null=True)),
                ('PCF', models.FloatField(blank=True, default=None, null=True)),
                ('PSR', models.FloatField(blank=True, default=None, null=True)),
                ('PB', models.FloatField(blank=True, default=None, null=True)),
                ('EPSD', models.FloatField(blank=True, default=None, null=True)),
                ('quick', models.FloatField(blank=True, default=None, null=True)),
                ('current', models.FloatField(blank=True, default=None, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockplot.Stock')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockfundamentals',
            unique_together=set([('stockid', 'date')]),
        ),
    ]
