# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockplot', '0009_auto_20160326_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='close',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='daily_traded_units',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='daily_turnover',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='high',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='last_price_of_the_day',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='low',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='traded_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='turnover',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
